---

tasks:
  - include_tasks: "docker.yml"
    when: docker_users

# Add "jenkins" to "docker" group
- name: docker users 
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
