---
# This playbook contains all actions that will be run

# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

# Import docker tasks
- name: Import docker tasks
  include_tasks: docker.yml

# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system
