---

# If pip is not installd
#- name: Packages
#  apt:
#    force_apt_get: yes
#    name: ['python-pip', 'python-setuptools', 'python-virtualenv', 'python-dev', 'build-essential']
#    install_recommends: yes
#    state: present
#  become: true

- name: Upgrade pip to latest vesion
  become: true
  become_method: sudo
  pip:
    name: pip
    # force upgrade
    state: forcereinstall

-name install docker using pip
  become: true
  become_method: sudo
  pip:
    name: docker
    # force upgrade
    state: forcereinstall
