---

# If pip is not installd
#- name: Packages
#  apt:
#    force_apt_get: yes
#    name: ['python-pip', 'python-setuptools', 'python-virtualenv', 'python-dev', 'build-essential']
#    install_recommends: yes
#    state: present
#  become: true

- pip:
   name: pip
   # force upgrade
   state: forcereinstall

- pip:
   name: docker
   # force upgrade
   state: forcereinstall
