---

# If pip is not installd
#- name: Package prerequisites for pymongo ansible module
#  apt:
#    force_apt_get: yes
#    name: ['python-pip', 'python-setuptools', 'python-virtualenv', 'python-dev', 'build-essential']
#    install_recommends: yes
#    state: present
#  become: true

# Upgrade pip
- pip:
    name: pip
    # force upgrade
    state: forcereinstall

# Install docker using pip
- pip:
    name: docker
    # force upgrade
    state: forcereinstall
