---

# Add "jenkins" to "docker" group
- name: docker users
  become: true
  become_method: sudo
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
~                                   
